variable "environment" {}
variable "cloudwatch_retention_period" {}
variable "region" {}
variable "gdx_url" {}
variable "auth_url" {}
variable "consumer_client_id" {}
variable "consumer_client_secret" {}
variable "lev_api_url" {}
variable "schedule" {}
