{
 "title": "Error Rates - Dev",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Server error rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "((sum(increase(http_server_requests_seconds_count{status=~\"4.*\"}[$__rate_interval])) * 100) OR vector(0)) / sum(increase(http_server_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "4XX error rate"
    },
    {
     "expr": "((sum(increase(http_server_requests_seconds_count{status=~\"5.*\"}[$__rate_interval])) * 100) OR vector(0)) / sum(increase(http_server_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "5XX error rate"
    }
   ]
  },
  {
   "title": "Server throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count[$__rate_interval])) OR vector(0)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Client error rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "((sum(increase(http_client_requests_seconds_count{status=~\"4.*\"}[$__rate_interval])) * 100) OR vector(0)) / sum(increase(http_client_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "4XX error rate"
    },
    {
     "expr": "((sum(increase(http_client_requests_seconds_count{status=~\"5.*\"}[$__rate_interval])) * 100) OR vector(0)) / sum(increase(http_client_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "5XX error rate"
    }
   ]
  },
  {
   "title": "Client throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_count[$__rate_interval])) OR vector(0)",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}