FROM grafana/grafana-enterprise:9.4.3
# This is just a placeholder for dependabot to check. If it updates this, you must copy the version to the ECS task
# definition terraform/shared/modules/grafana/ecs
