{
 "title": "Base Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Server requests by URI and method",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(uri, method) (increase(http_server_requests_seconds_count{uri=~\"/events.*\"}[5m]))",
     "legendFormat": "{{uri}} - {{method}}"
    }
   ]
  },
  {
   "title": "Data enrichment calls",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"/events/{id}\", method=\"GET\"}[1m]))",
     "legendFormat": "Get event from GDX"
    },
    {
     "expr": "sum by(outcome) (increase(http_client_requests_seconds_count{uri=\"/v1/registration/death/{id}\"}[1m]))",
     "legendFormat": "Get details from LEV - Outcome = {{outcome}}"
    },
    {}
   ]
  },
  {
   "title": "Event actions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(EVENT_ACTION_EventPublished_total[1m]))",
     "legendFormat": "Event published"
    },
    {
     "expr": "sum(increase(EVENT_ACTION_EventDeleted_total[1m]))",
     "legendFormat": "Event deleted"
    }
   ]
  }
 ]
}